name: 'Pull Request'
on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: v21.1.0
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Cache NPM dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: npm-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          npm-cache-${{ runner.os }}-

    - name: Install Dependencies and Build
      run: |
        npm ci
        npx prisma generate
        npm run build:prod
      env:
        CI: true

    - name: Cache Prisma Binary
      uses: actions/cache@v4
      with:
        path: ~/.npm/_npx
        key: prisma-binary-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
        restore-keys: prisma-binary-${{ runner.os }}-
